// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Contact from './Contact/index.svelte';
import ContentIndex from './ContentIndex/index.svelte';
import Experience from './Experience/index.svelte';
import Home from './Home/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import RichText from './RichText/index.svelte';
import Skills from './Skills/index.svelte';
import VideoBlock from './VideoBlock/index.svelte';

export const components = {
	biography: Biography,
	contact: Contact,
	content_index: ContentIndex,
	experience: Experience,
	home: Home,
	image_block: ImageBlock,
	rich_text: RichText,
	tech_list: Skills,
	video_block: VideoBlock
};
